import chemical_kinetics_thermodynamics_heat_transfer_foundation_canonical_lane_mathlib.GateLemmas
import chemical_kinetics_thermodynamics_heat_transfer_foundation_canonical_lane_mathlib.FinalTheorem
